CREATE TABLE `creations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`text` text NOT NULL,
	`format` enum('square','portrait','story') NOT NULL DEFAULT 'portrait',
	`model` enum('classic','bold','fade','highlight') NOT NULL DEFAULT 'classic',
	`backgroundImageUrl` text,
	`backgroundImageKey` text,
	`fontSize` int NOT NULL DEFAULT 100,
	`font` varchar(32) NOT NULL DEFAULT 'Inter',
	`textColor` enum('white','black') NOT NULL DEFAULT 'white',
	`textOutline` int NOT NULL DEFAULT 0,
	`alignHorizontal` enum('left','center','right') NOT NULL DEFAULT 'center',
	`alignVertical` enum('top','middle','bottom') NOT NULL DEFAULT 'middle',
	`fadeOverlay` int NOT NULL DEFAULT 50,
	`blur` int NOT NULL DEFAULT 0,
	`brightness` int NOT NULL DEFAULT 100,
	`contrast` int NOT NULL DEFAULT 100,
	`exportedImageUrl` text,
	`exportedImageKey` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `creations_id` PRIMARY KEY(`id`)
);
